name: Install

on:
  - push

jobs:
  build:
    env:
      OCAML_VERSION: 4.09.1
      OPAMYES: 1
      OPAMJOBS: 2
      OPAMVERBOSE: 1
      INFER_OPAM_SWITCH: "ocaml-variants.${OCAML_VERSION}+flambda"
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.09.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Restore opam cache
        uses: actions/cache@v2
        with:
          path: ${HOME}/.opam
          key: ${{ runner.os }}-${{ hashFiles('.opam') }}

      - run: opam remove infer || true

      - run: opam update --upgrade

      - run: opam pin add --no-action infer .

      - run: opam depext --update infer;
        if: runner.os != 'macOS'

      - run: opam install --deps-only infer

      - run: opam install infer

      - run: opam remove infer || true
